import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=fs.readFileSync('assets/forms.js','utf8').replace(/^import .*?;\s*/s,'').replace('export async function initForms','async function initForms');
const nodes=new Map();
const node=key=>{if(!nodes.has(key))nodes.set(key,{innerHTML:'',textContent:'',addEventListener(){}});return nodes.get(key);};
const root={innerHTML:'',querySelector:node,addEventListener(){}};
let writes=[], readPath, records=[];
const sandbox={document:{getElementById:()=>root},auth:{currentUser:{uid:'employee-a',email:'a@example.com'}},db:{},collection:(...x)=>x.slice(1),doc:(...x)=>x.slice(1),getDocs:async()=>({docs:records}),getDoc:async path=>{readPath=path;return {exists:()=>false};},setDoc:async(path,data)=>writes.push({path,data}),serverTimestamp:()=> 'server-time',FormData:class {constructor(values){this.values=values.values;}get(k){return this.values[k];}},setTimeout,console};
vm.createContext(sandbox);
vm.runInContext(source,sandbox);
await vm.runInContext('initForms(false)',sandbox);
assert.match(node('#formList').innerHTML,/工作服尺寸/);
assert.doesNotMatch(node('#formList').innerHTML,/查看回覆|新增表單/);
await vm.runInContext("fill('uniform-sizes')",sandbox);
assert.equal(readPath.join('/'),'forms/uniform-sizes/responses/employee-a');
assert.match(node('#formAnswer').innerHTML,/肩寬（cm）/);
assert.match(node('#formAnswer').innerHTML,/背後的名字/);
const button={disabled:false};
sandbox.event={preventDefault(){},target:{values:{f0:'170',f1:'65',f2:'45',f3:'100',f4:'70',f5:'60',f6:'一般',f7:'Alex'},querySelector:()=>button}};
await vm.runInContext('saveAnswer(event)',sandbox);
assert.equal(writes.length,1);assert.equal(writes[0].path.join('/'),'forms/uniform-sizes/responses/employee-a');assert.equal(writes[0].data.answers[0],170);assert.equal(writes[0].data.answers[7],'Alex');assert.equal(button.disabled,false);
sandbox.event.target.values.f7='   ';
await vm.runInContext('saveAnswer(event)',sandbox);
assert.equal(writes.length,1);assert.match(node('[role="status"]').textContent,/必填/);
await vm.runInContext('initForms(true)',sandbox);
assert.match(node('#formList').innerHTML,/查看回覆/);
records=[{id:'custom',data:()=>({title:'其他表單',description:'',open:false,fields:[{label:'備註',type:'text',required:false,options:[]}]})}];
await vm.runInContext('initForms(false)',sandbox);
await vm.runInContext("fill('custom')",sandbox);
assert.match(node('#formAnswer').innerHTML,/fieldset disabled/);
assert.doesNotMatch(node('#formAnswer').innerHTML,/type="submit"/);
console.log('PASS: built-in form, role controls, own response path, numeric storage, required whitespace, closed form');
